chore: Fix new clippy lint (#276)
```bash
error: unit tests in doctest are not executed
  --> src/proptest.rs:94:9
   |
94 | ///     #[test]
   |         ^^^^^^^
   |
```

This is just a usage example, so the block can be ignored for doctests